DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS assignment;
DROP TABLE IF EXISTS grade;

CREATE TABLE student (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
);

CREATE TABLE assignment (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT UNIQUE NOT NULL,
  weight REAL NOT NULL,
  due_date DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE grade (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  score REAL NOT NULL,
  submit_date DATE NOT NULL DEFAULT CURRENT_DATE,
  student_id INTEGER NOT NULL,
  assignment_id INTEGER NOT NULL,
  FOREIGN KEY (student_id) REFERENCES student (id),
  FOREIGN KEY (assignment_id) REFERENCES assignment (id)
);